{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [ 100.0, 100.0, 820.0, 460.0 ],
		"bglocked": 0,
		"openinpresentation": 0,
		"boxes": [
			{ "box": { "id": "obj-24", "maxclass": "comment", "text": "AWH Capture Tap — passthrough + sfrecord~, driven over OSC (see m4l/README.md). In: /awh/record <path>, /awh/stop, /awh/loop <startBeat> <lengthBeats>, /awh/play <0|1>, /awh/ping.", "patching_rect": [ 30.0, 5.0, 720.0, 20.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-1", "maxclass": "newobj", "text": "udpreceive 9720", "patching_rect": [ 30.0, 35.0, 110.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-2", "maxclass": "newobj", "text": "route /awh/record /awh/stop /awh/loop /awh/play /awh/ping", "patching_rect": [ 30.0, 70.0, 380.0, 22.0 ], "numinlets": 1, "numoutlets": 6, "outlettype": [ "", "", "", "", "", "" ] } },
			{ "box": { "id": "obj-3", "maxclass": "newobj", "text": "t b s", "patching_rect": [ 30.0, 110.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "bang", "" ] } },
			{ "box": { "id": "obj-4", "maxclass": "newobj", "text": "prepend open", "patching_rect": [ 95.0, 150.0, 90.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-5", "maxclass": "newobj", "text": "del 100", "patching_rect": [ 30.0, 150.0, 55.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "bang" ] } },
			{ "box": { "id": "obj-6", "maxclass": "message", "text": "1", "patching_rect": [ 30.0, 190.0, 29.5, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-7", "maxclass": "message", "text": "0", "patching_rect": [ 150.0, 110.0, 29.5, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-8", "maxclass": "newobj", "text": "sfrecord~ 2", "patching_rect": [ 30.0, 320.0, 80.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ] } },
			{ "box": { "id": "obj-9", "maxclass": "newobj", "text": "plugin~", "patching_rect": [ 200.0, 280.0, 55.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "signal", "signal" ] } },
			{ "box": { "id": "obj-10", "maxclass": "newobj", "text": "plugout~", "patching_rect": [ 200.0, 360.0, 62.0, 22.0 ], "numinlets": 2, "numoutlets": 2, "outlettype": [ "signal", "signal" ] } },
			{ "box": { "id": "obj-11", "maxclass": "newobj", "text": "unpack 0. 0.", "patching_rect": [ 230.0, 110.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ] } },
			{ "box": { "id": "obj-12", "maxclass": "message", "text": "set loop_start \\$1", "patching_rect": [ 230.0, 150.0, 105.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-13", "maxclass": "newobj", "text": "t b f", "patching_rect": [ 320.0, 150.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "bang", "float" ] } },
			{ "box": { "id": "obj-14", "maxclass": "message", "text": "set loop_length \\$1", "patching_rect": [ 320.0, 190.0, 112.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-15", "maxclass": "message", "text": "set loop 1", "patching_rect": [ 440.0, 190.0, 66.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-16", "maxclass": "newobj", "text": "sel 1 0", "patching_rect": [ 520.0, 110.0, 50.0, 22.0 ], "numinlets": 3, "numoutlets": 3, "outlettype": [ "bang", "bang", "" ] } },
			{ "box": { "id": "obj-17", "maxclass": "message", "text": "call start_playing", "patching_rect": [ 520.0, 150.0, 105.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-18", "maxclass": "message", "text": "call stop_playing", "patching_rect": [ 585.0, 190.0, 103.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-19", "maxclass": "newobj", "text": "loadbang", "patching_rect": [ 660.0, 35.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "bang" ] } },
			{ "box": { "id": "obj-20", "maxclass": "newobj", "text": "live.path live_set", "patching_rect": [ 660.0, 70.0, 100.0, 22.0 ], "numinlets": 1, "numoutlets": 3, "outlettype": [ "", "", "" ] } },
			{ "box": { "id": "obj-21", "maxclass": "newobj", "text": "live.object", "patching_rect": [ 520.0, 250.0, 70.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-22", "maxclass": "message", "text": "/awh/pong 1", "patching_rect": [ 620.0, 110.0, 80.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-23", "maxclass": "newobj", "text": "udpsend 127.0.0.1 9721", "patching_rect": [ 620.0, 320.0, 145.0, 22.0 ], "numinlets": 1, "numoutlets": 0 } }
		],
		"lines": [
			{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-2", 0 ] } },
			{ "patchline": { "source": [ "obj-2", 0 ], "destination": [ "obj-3", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 1 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-4", 0 ], "destination": [ "obj-8", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 0 ], "destination": [ "obj-5", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 0 ], "destination": [ "obj-6", 0 ] } },
			{ "patchline": { "source": [ "obj-6", 0 ], "destination": [ "obj-8", 0 ] } },
			{ "patchline": { "source": [ "obj-2", 1 ], "destination": [ "obj-7", 0 ] } },
			{ "patchline": { "source": [ "obj-7", 0 ], "destination": [ "obj-8", 0 ] } },
			{ "patchline": { "source": [ "obj-2", 2 ], "destination": [ "obj-11", 0 ] } },
			{ "patchline": { "source": [ "obj-11", 0 ], "destination": [ "obj-12", 0 ] } },
			{ "patchline": { "source": [ "obj-12", 0 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-11", 1 ], "destination": [ "obj-13", 0 ] } },
			{ "patchline": { "source": [ "obj-13", 1 ], "destination": [ "obj-14", 0 ] } },
			{ "patchline": { "source": [ "obj-14", 0 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-13", 0 ], "destination": [ "obj-15", 0 ] } },
			{ "patchline": { "source": [ "obj-15", 0 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-2", 3 ], "destination": [ "obj-16", 0 ] } },
			{ "patchline": { "source": [ "obj-16", 0 ], "destination": [ "obj-17", 0 ] } },
			{ "patchline": { "source": [ "obj-16", 1 ], "destination": [ "obj-18", 0 ] } },
			{ "patchline": { "source": [ "obj-17", 0 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-18", 0 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-2", 4 ], "destination": [ "obj-22", 0 ] } },
			{ "patchline": { "source": [ "obj-22", 0 ], "destination": [ "obj-23", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 0 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-20", 0 ], "destination": [ "obj-21", 1 ] } },
			{ "patchline": { "source": [ "obj-9", 0 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-9", 1 ], "destination": [ "obj-10", 1 ] } },
			{ "patchline": { "source": [ "obj-9", 0 ], "destination": [ "obj-8", 0 ] } },
			{ "patchline": { "source": [ "obj-9", 1 ], "destination": [ "obj-8", 1 ] } }
		]
	}
}
