{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [ 100.0, 100.0, 1400.0, 800.0 ],
		"bglocked": 0,
		"openinpresentation": 0,
		"boxes": [
			{ "box": { "id": "obj-1", "maxclass": "comment", "text": "AWH Ducker — transport-synced sidechain gain envelope, OSC-driven (see m4l/README.md). In: /awh/duck/ping, /awh/duck/shape <atk> <hold> <rel> <depth>, /awh/duck/triggers <patLenBeats> <beat0> <beat1> ..., /awh/duck/on <0|1>, /awh/duck/status.", "patching_rect": [ 30.0, 5.0, 900.0, 30.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-2", "maxclass": "newobj", "text": "udpreceive 9722", "patching_rect": [ 30.0, 45.0, 110.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-3", "maxclass": "newobj", "text": "route /awh/duck/ping /awh/duck/shape /awh/duck/triggers /awh/duck/on /awh/duck/status", "patching_rect": [ 30.0, 80.0, 560.0, 22.0 ], "numinlets": 1, "numoutlets": 6, "outlettype": ["","","","","",""] } },
			{ "box": { "id": "obj-4", "maxclass": "message", "text": "/awh/duck/pong 1", "patching_rect": [ 30.0, 120.0, 110.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-5", "maxclass": "newobj", "text": "unpack 0. 0. 0. 0.", "patching_rect": [ 170.0, 120.0, 130.0, 22.0 ], "numinlets": 1, "numoutlets": 4, "outlettype": ["float","float","float","float"] } },
			{ "box": { "id": "obj-6", "maxclass": "newobj", "text": "value attack", "patching_rect": [ 170.0, 160.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-7", "maxclass": "newobj", "text": "value hold", "patching_rect": [ 260.0, 160.0, 75.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-8", "maxclass": "newobj", "text": "value release", "patching_rect": [ 340.0, 160.0, 85.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-9", "maxclass": "newobj", "text": "value depth", "patching_rect": [ 430.0, 160.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-10", "maxclass": "newobj", "text": "zl slice 1", "patching_rect": [ 520.0, 120.0, 80.0, 22.0 ], "numinlets": 2, "numoutlets": 2, "outlettype": ["",""] } },
			{ "box": { "id": "obj-11", "maxclass": "newobj", "text": "unpack 0.", "patching_rect": [ 520.0, 160.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": ["float"] } },
			{ "box": { "id": "obj-12", "maxclass": "newobj", "text": "value patlen", "patching_rect": [ 520.0, 200.0, 85.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-13", "maxclass": "newobj", "text": "zl len", "patching_rect": [ 620.0, 160.0, 60.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": ["int"] } },
			{ "box": { "id": "obj-14", "maxclass": "newobj", "text": "value trigcount", "patching_rect": [ 620.0, 200.0, 95.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-15", "maxclass": "newobj", "text": "value trigbeats", "patching_rect": [ 710.0, 160.0, 95.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-16", "maxclass": "newobj", "text": "value on", "patching_rect": [ 830.0, 120.0, 70.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-17", "maxclass": "newobj", "text": "sel 0", "patching_rect": [ 830.0, 160.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang",""] } },
			{ "box": { "id": "obj-18", "maxclass": "message", "text": "1.", "patching_rect": [ 830.0, 480.0, 29.5, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-19", "maxclass": "newobj", "text": "t b b b b b b", "patching_rect": [ 30.0, 160.0, 200.0, 22.0 ], "numinlets": 1, "numoutlets": 6, "outlettype": ["bang","bang","bang","bang","bang","bang"] } },
			{ "box": { "id": "obj-20", "maxclass": "newobj", "text": "value trigcount", "patching_rect": [ 30.0, 200.0, 95.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-21", "maxclass": "newobj", "text": "value depth", "patching_rect": [ 130.0, 200.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-22", "maxclass": "newobj", "text": "value release", "patching_rect": [ 215.0, 200.0, 85.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-23", "maxclass": "newobj", "text": "value hold", "patching_rect": [ 305.0, 200.0, 75.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-24", "maxclass": "newobj", "text": "value attack", "patching_rect": [ 385.0, 200.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-25", "maxclass": "newobj", "text": "value on", "patching_rect": [ 470.0, 200.0, 70.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-26", "maxclass": "newobj", "text": "pack 0 0. 0. 0. 0. 0", "patching_rect": [ 30.0, 240.0, 190.0, 22.0 ], "numinlets": 6, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-27", "maxclass": "newobj", "text": "prepend /awh/duck/status", "patching_rect": [ 30.0, 280.0, 160.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-28", "maxclass": "newobj", "text": "udpsend 127.0.0.1 9723", "patching_rect": [ 30.0, 320.0, 150.0, 22.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-29", "maxclass": "newobj", "text": "loadbang", "patching_rect": [ 960.0, 45.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"] } },
			{ "box": { "id": "obj-30", "maxclass": "newobj", "text": "live.path live_set", "patching_rect": [ 960.0, 80.0, 105.0, 22.0 ], "numinlets": 1, "numoutlets": 3, "outlettype": ["","",""] } },
			{ "box": { "id": "obj-31", "maxclass": "newobj", "text": "live.object", "patching_rect": [ 1000.0, 400.0, 75.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-32", "maxclass": "message", "text": "1", "patching_rect": [ 960.0, 120.0, 29.5, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-33", "maxclass": "message", "text": "-1.", "patching_rect": [ 1040.0, 120.0, 35.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-34", "maxclass": "newobj", "text": "metro 1", "patching_rect": [ 960.0, 160.0, 60.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": ["bang"] } },
			{ "box": { "id": "obj-35", "maxclass": "newobj", "text": "t b b", "patching_rect": [ 960.0, 200.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang","bang"] } },
			{ "box": { "id": "obj-36", "maxclass": "message", "text": "get is_playing", "patching_rect": [ 1030.0, 240.0, 100.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-37", "maxclass": "message", "text": "get current_song_time", "patching_rect": [ 960.0, 240.0, 140.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-38", "maxclass": "newobj", "text": "route current_song_time is_playing", "patching_rect": [ 1000.0, 440.0, 220.0, 22.0 ], "numinlets": 1, "numoutlets": 3, "outlettype": ["","",""] } },
			{ "box": { "id": "obj-39", "maxclass": "newobj", "text": "value isplaying", "patching_rect": [ 1240.0, 440.0, 95.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-40", "maxclass": "newobj", "text": "expr fmod($f1,$f2)", "patching_rect": [ 1000.0, 480.0, 140.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": ["float"] } },
			{ "box": { "id": "obj-41", "maxclass": "newobj", "text": "t b f", "patching_rect": [ 1000.0, 520.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang","float"] } },
			{ "box": { "id": "obj-42", "maxclass": "newobj", "text": "value curmod", "patching_rect": [ 1000.0, 560.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-43", "maxclass": "newobj", "text": "value isplaying", "patching_rect": [ 1100.0, 560.0, 95.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-44", "maxclass": "newobj", "text": "sel 0", "patching_rect": [ 1100.0, 600.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang",""] } },
			{ "box": { "id": "obj-45", "maxclass": "message", "text": "-1.", "patching_rect": [ 1160.0, 600.0, 35.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-46", "maxclass": "newobj", "text": "value prevbeat", "patching_rect": [ 1160.0, 640.0, 90.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-47", "maxclass": "newobj", "text": "t b b", "patching_rect": [ 1100.0, 640.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang","bang"] } },
			{ "box": { "id": "obj-48", "maxclass": "newobj", "text": "value prevbeat", "patching_rect": [ 1100.0, 680.0, 90.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-49", "maxclass": "newobj", "text": "value curmod", "patching_rect": [ 1200.0, 680.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-50", "maxclass": "newobj", "text": "expr ($f1 < 0) || ($f2 < $f1)", "patching_rect": [ 1100.0, 720.0, 190.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": ["int"] } },
			{ "box": { "id": "obj-51", "maxclass": "newobj", "text": "sel 1", "patching_rect": [ 1100.0, 760.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang",""] } },
			{ "box": { "id": "obj-52", "maxclass": "newobj", "text": "value curmod", "patching_rect": [ 1200.0, 760.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-53", "maxclass": "newobj", "text": "t b", "patching_rect": [ 1100.0, 800.0, 40.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"] } },
			{ "box": { "id": "obj-54", "maxclass": "newobj", "text": "t b b", "patching_rect": [ 1100.0, 840.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang","bang"] } },
			{ "box": { "id": "obj-55", "maxclass": "newobj", "text": "value trigcount", "patching_rect": [ 1180.0, 840.0, 95.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-56", "maxclass": "newobj", "text": "uzi 0 0", "patching_rect": [ 1100.0, 880.0, 70.0, 22.0 ], "numinlets": 2, "numoutlets": 2, "outlettype": ["int","bang"] } },
			{ "box": { "id": "obj-57", "maxclass": "newobj", "text": "t b i", "patching_rect": [ 1100.0, 920.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang","int"] } },
			{ "box": { "id": "obj-58", "maxclass": "newobj", "text": "zl nth 0", "patching_rect": [ 1100.0, 960.0, 70.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-59", "maxclass": "newobj", "text": "value trigbeats", "patching_rect": [ 1200.0, 960.0, 95.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-60", "maxclass": "newobj", "text": "expr ($f1 > $f2) && ($f1 <= $f3)", "patching_rect": [ 1100.0, 1000.0, 220.0, 22.0 ], "numinlets": 3, "numoutlets": 1, "outlettype": ["int"] } },
			{ "box": { "id": "obj-61", "maxclass": "newobj", "text": "sel 1", "patching_rect": [ 1100.0, 1040.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang",""] } },
			{ "box": { "id": "obj-62", "maxclass": "newobj", "text": "value on", "patching_rect": [ 1180.0, 1040.0, 70.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-63", "maxclass": "newobj", "text": "sel 1", "patching_rect": [ 1180.0, 1080.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["bang",""] } },
			{ "box": { "id": "obj-64", "maxclass": "newobj", "text": "t b b b b", "patching_rect": [ 1180.0, 1120.0, 70.0, 22.0 ], "numinlets": 1, "numoutlets": 4, "outlettype": ["bang","bang","bang","bang"] } },
			{ "box": { "id": "obj-65", "maxclass": "newobj", "text": "value release", "patching_rect": [ 1180.0, 1160.0, 85.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-66", "maxclass": "newobj", "text": "value hold", "patching_rect": [ 1280.0, 1160.0, 75.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-67", "maxclass": "newobj", "text": "value attack", "patching_rect": [ 1370.0, 1160.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-68", "maxclass": "newobj", "text": "value depth", "patching_rect": [ 1460.0, 1160.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-69", "maxclass": "newobj", "text": "* -1.", "patching_rect": [ 1460.0, 1200.0, 55.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": ["float"] } },
			{ "box": { "id": "obj-70", "maxclass": "newobj", "text": "dbtoa", "patching_rect": [ 1460.0, 1240.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": ["float"] } },
			{ "box": { "id": "obj-71", "maxclass": "newobj", "text": "pack 0. 0. 0. 0.", "patching_rect": [ 1180.0, 1280.0, 140.0, 22.0 ], "numinlets": 4, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-72", "maxclass": "message", "text": "$1 $2, $1 $3, 1. $4", "patching_rect": [ 1180.0, 1320.0, 160.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [""] } },
			{ "box": { "id": "obj-73", "maxclass": "newobj", "text": "line~", "patching_rect": [ 1180.0, 1360.0, 60.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
			{ "box": { "id": "obj-74", "maxclass": "newobj", "text": "plugin~", "patching_rect": [ 200.0, 400.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": ["signal","signal"] } },
			{ "box": { "id": "obj-75", "maxclass": "newobj", "text": "*~", "patching_rect": [ 200.0, 460.0, 55.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
			{ "box": { "id": "obj-76", "maxclass": "newobj", "text": "*~", "patching_rect": [ 300.0, 460.0, 55.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
			{ "box": { "id": "obj-77", "maxclass": "newobj", "text": "plugout~", "patching_rect": [ 200.0, 520.0, 65.0, 22.0 ], "numinlets": 2, "numoutlets": 2, "outlettype": ["signal","signal"] } }
		],
		"lines": [
			{ "patchline": { "source": [ "obj-2", 0 ], "destination": [ "obj-3", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 1 ], "destination": [ "obj-5", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 0 ], "destination": [ "obj-6", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 1 ], "destination": [ "obj-7", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 2 ], "destination": [ "obj-8", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 3 ], "destination": [ "obj-9", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 2 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-10", 0 ], "destination": [ "obj-11", 0 ] } },
			{ "patchline": { "source": [ "obj-11", 0 ], "destination": [ "obj-12", 0 ] } },
			{ "patchline": { "source": [ "obj-10", 1 ], "destination": [ "obj-13", 0 ] } },
			{ "patchline": { "source": [ "obj-13", 0 ], "destination": [ "obj-14", 0 ] } },
			{ "patchline": { "source": [ "obj-10", 1 ], "destination": [ "obj-15", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 3 ], "destination": [ "obj-16", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 3 ], "destination": [ "obj-17", 0 ] } },
			{ "patchline": { "source": [ "obj-17", 0 ], "destination": [ "obj-18", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 4 ], "destination": [ "obj-19", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 5 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 4 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 3 ], "destination": [ "obj-22", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 2 ], "destination": [ "obj-23", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 1 ], "destination": [ "obj-24", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 0 ], "destination": [ "obj-25", 0 ] } },
			{ "patchline": { "source": [ "obj-25", 0 ], "destination": [ "obj-26", 0 ] } },
			{ "patchline": { "source": [ "obj-24", 0 ], "destination": [ "obj-26", 1 ] } },
			{ "patchline": { "source": [ "obj-23", 0 ], "destination": [ "obj-26", 2 ] } },
			{ "patchline": { "source": [ "obj-22", 0 ], "destination": [ "obj-26", 3 ] } },
			{ "patchline": { "source": [ "obj-21", 0 ], "destination": [ "obj-26", 4 ] } },
			{ "patchline": { "source": [ "obj-20", 0 ], "destination": [ "obj-26", 5 ] } },
			{ "patchline": { "source": [ "obj-26", 0 ], "destination": [ "obj-27", 0 ] } },
			{ "patchline": { "source": [ "obj-4", 0 ], "destination": [ "obj-28", 0 ] } },
			{ "patchline": { "source": [ "obj-27", 0 ], "destination": [ "obj-28", 0 ] } },
			{ "patchline": { "source": [ "obj-29", 0 ], "destination": [ "obj-30", 0 ] } },
			{ "patchline": { "source": [ "obj-30", 0 ], "destination": [ "obj-31", 1 ] } },
			{ "patchline": { "source": [ "obj-29", 0 ], "destination": [ "obj-32", 0 ] } },
			{ "patchline": { "source": [ "obj-29", 0 ], "destination": [ "obj-33", 0 ] } },
			{ "patchline": { "source": [ "obj-32", 0 ], "destination": [ "obj-34", 0 ] } },
			{ "patchline": { "source": [ "obj-34", 0 ], "destination": [ "obj-35", 0 ] } },
			{ "patchline": { "source": [ "obj-35", 1 ], "destination": [ "obj-36", 0 ] } },
			{ "patchline": { "source": [ "obj-35", 0 ], "destination": [ "obj-37", 0 ] } },
			{ "patchline": { "source": [ "obj-36", 0 ], "destination": [ "obj-31", 0 ] } },
			{ "patchline": { "source": [ "obj-37", 0 ], "destination": [ "obj-31", 0 ] } },
			{ "patchline": { "source": [ "obj-31", 0 ], "destination": [ "obj-38", 0 ] } },
			{ "patchline": { "source": [ "obj-38", 1 ], "destination": [ "obj-39", 0 ] } },
			{ "patchline": { "source": [ "obj-38", 0 ], "destination": [ "obj-40", 0 ] } },
			{ "patchline": { "source": [ "obj-11", 0 ], "destination": [ "obj-40", 1 ] } },
			{ "patchline": { "source": [ "obj-40", 0 ], "destination": [ "obj-41", 0 ] } },
			{ "patchline": { "source": [ "obj-41", 1 ], "destination": [ "obj-42", 0 ] } },
			{ "patchline": { "source": [ "obj-41", 0 ], "destination": [ "obj-43", 0 ] } },
			{ "patchline": { "source": [ "obj-43", 0 ], "destination": [ "obj-44", 0 ] } },
			{ "patchline": { "source": [ "obj-44", 0 ], "destination": [ "obj-18", 0 ] } },
			{ "patchline": { "source": [ "obj-44", 0 ], "destination": [ "obj-45", 0 ] } },
			{ "patchline": { "source": [ "obj-45", 0 ], "destination": [ "obj-46", 0 ] } },
			{ "patchline": { "source": [ "obj-33", 0 ], "destination": [ "obj-46", 0 ] } },
			{ "patchline": { "source": [ "obj-44", 1 ], "destination": [ "obj-47", 0 ] } },
			{ "patchline": { "source": [ "obj-47", 0 ], "destination": [ "obj-48", 0 ] } },
			{ "patchline": { "source": [ "obj-47", 1 ], "destination": [ "obj-49", 0 ] } },
			{ "patchline": { "source": [ "obj-49", 0 ], "destination": [ "obj-50", 1 ] } },
			{ "patchline": { "source": [ "obj-48", 0 ], "destination": [ "obj-50", 0 ] } },
			{ "patchline": { "source": [ "obj-50", 0 ], "destination": [ "obj-51", 0 ] } },
			{ "patchline": { "source": [ "obj-51", 0 ], "destination": [ "obj-52", 0 ] } },
			{ "patchline": { "source": [ "obj-52", 0 ], "destination": [ "obj-46", 0 ] } },
			{ "patchline": { "source": [ "obj-51", 1 ], "destination": [ "obj-53", 0 ] } },
			{ "patchline": { "source": [ "obj-53", 0 ], "destination": [ "obj-54", 0 ] } },
			{ "patchline": { "source": [ "obj-54", 1 ], "destination": [ "obj-55", 0 ] } },
			{ "patchline": { "source": [ "obj-55", 0 ], "destination": [ "obj-56", 1 ] } },
			{ "patchline": { "source": [ "obj-54", 0 ], "destination": [ "obj-56", 0 ] } },
			{ "patchline": { "source": [ "obj-56", 0 ], "destination": [ "obj-57", 0 ] } },
			{ "patchline": { "source": [ "obj-57", 1 ], "destination": [ "obj-58", 1 ] } },
			{ "patchline": { "source": [ "obj-57", 0 ], "destination": [ "obj-59", 0 ] } },
			{ "patchline": { "source": [ "obj-59", 0 ], "destination": [ "obj-58", 0 ] } },
			{ "patchline": { "source": [ "obj-58", 0 ], "destination": [ "obj-60", 0 ] } },
			{ "patchline": { "source": [ "obj-48", 0 ], "destination": [ "obj-60", 1 ] } },
			{ "patchline": { "source": [ "obj-49", 0 ], "destination": [ "obj-60", 2 ] } },
			{ "patchline": { "source": [ "obj-60", 0 ], "destination": [ "obj-61", 0 ] } },
			{ "patchline": { "source": [ "obj-61", 0 ], "destination": [ "obj-62", 0 ] } },
			{ "patchline": { "source": [ "obj-62", 0 ], "destination": [ "obj-63", 0 ] } },
			{ "patchline": { "source": [ "obj-56", 1 ], "destination": [ "obj-52", 0 ] } },
			{ "patchline": { "source": [ "obj-63", 0 ], "destination": [ "obj-64", 0 ] } },
			{ "patchline": { "source": [ "obj-64", 3 ], "destination": [ "obj-65", 0 ] } },
			{ "patchline": { "source": [ "obj-64", 2 ], "destination": [ "obj-66", 0 ] } },
			{ "patchline": { "source": [ "obj-64", 1 ], "destination": [ "obj-67", 0 ] } },
			{ "patchline": { "source": [ "obj-64", 0 ], "destination": [ "obj-68", 0 ] } },
			{ "patchline": { "source": [ "obj-68", 0 ], "destination": [ "obj-69", 0 ] } },
			{ "patchline": { "source": [ "obj-69", 0 ], "destination": [ "obj-70", 0 ] } },
			{ "patchline": { "source": [ "obj-70", 0 ], "destination": [ "obj-71", 0 ] } },
			{ "patchline": { "source": [ "obj-67", 0 ], "destination": [ "obj-71", 1 ] } },
			{ "patchline": { "source": [ "obj-66", 0 ], "destination": [ "obj-71", 2 ] } },
			{ "patchline": { "source": [ "obj-65", 0 ], "destination": [ "obj-71", 3 ] } },
			{ "patchline": { "source": [ "obj-71", 0 ], "destination": [ "obj-72", 0 ] } },
			{ "patchline": { "source": [ "obj-72", 0 ], "destination": [ "obj-73", 0 ] } },
			{ "patchline": { "source": [ "obj-18", 0 ], "destination": [ "obj-73", 0 ] } },
			{ "patchline": { "source": [ "obj-74", 0 ], "destination": [ "obj-75", 0 ] } },
			{ "patchline": { "source": [ "obj-74", 1 ], "destination": [ "obj-76", 0 ] } },
			{ "patchline": { "source": [ "obj-73", 0 ], "destination": [ "obj-75", 1 ] } },
			{ "patchline": { "source": [ "obj-73", 0 ], "destination": [ "obj-76", 1 ] } },
			{ "patchline": { "source": [ "obj-75", 0 ], "destination": [ "obj-77", 0 ] } },
			{ "patchline": { "source": [ "obj-76", 0 ], "destination": [ "obj-77", 1 ] } }
		]
	}
}
