{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [ 100.0, 100.0, 1400.0, 1480.0 ],
		"bglocked": 0,
		"openinpresentation": 0,
		"boxes": [
			{ "box": { "id": "obj-1", "maxclass": "comment", "text": "AWH Remote — transport + clip launch, OSC-driven (m4l/README.md). Supersedes AWH Capture Tap: same 9720/9721 ports, superset protocol. In: /awh/record <path>, /awh/stop, /awh/loop <startBeat> <lenBeats>, /awh/play <0|1>, /awh/ping, /awh/fire <trackIdx> <slotIdx>, /awh/scene <sceneIdx>, /awh/stopclips <trackIdx (-1=all)>, /awh/jump <beats>. Replies (fire/scene/stopclips/jump only): /awh/status <action> ..., /awh/error <text>.", "patching_rect": [ 30.0, 5.0, 1050.0, 40.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-2", "maxclass": "newobj", "text": "udpreceive 9720", "patching_rect": [ 30.0, 50.0, 110.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-3", "maxclass": "newobj", "text": "route /awh/record /awh/stop /awh/loop /awh/play /awh/ping /awh/fire /awh/scene /awh/stopclips /awh/jump", "patching_rect": [ 30.0, 85.0, 900.0, 22.0 ], "numinlets": 1, "numoutlets": 10, "outlettype": [ "", "", "", "", "", "", "", "", "", "" ] } },
			{ "box": { "id": "obj-4", "maxclass": "newobj", "text": "udpsend 127.0.0.1 9721", "patching_rect": [ 30.0, 1440.0, 150.0, 22.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-5", "maxclass": "newobj", "text": "t b s", "patching_rect": [ 30.0, 130.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "bang", "" ] } },
			{ "box": { "id": "obj-6", "maxclass": "message", "text": "prepend open", "patching_rect": [ 95.0, 170.0, 90.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-7", "maxclass": "newobj", "text": "del 100", "patching_rect": [ 30.0, 170.0, 55.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "bang" ] } },
			{ "box": { "id": "obj-8", "maxclass": "message", "text": "1", "patching_rect": [ 30.0, 210.0, 29.5, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-9", "maxclass": "message", "text": "0", "patching_rect": [ 150.0, 130.0, 29.5, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-10", "maxclass": "newobj", "text": "sfrecord~ 2", "patching_rect": [ 30.0, 250.0, 80.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ] } },
			{ "box": { "id": "obj-11", "maxclass": "newobj", "text": "plugin~", "patching_rect": [ 200.0, 210.0, 55.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "signal", "signal" ] } },
			{ "box": { "id": "obj-12", "maxclass": "newobj", "text": "plugout~", "patching_rect": [ 200.0, 290.0, 62.0, 22.0 ], "numinlets": 2, "numoutlets": 2, "outlettype": [ "signal", "signal" ] } },
			{ "box": { "id": "obj-13", "maxclass": "newobj", "text": "unpack 0. 0.", "patching_rect": [ 230.0, 130.0, 80.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ] } },
			{ "box": { "id": "obj-14", "maxclass": "message", "text": "set loop_start $1", "patching_rect": [ 230.0, 170.0, 105.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-15", "maxclass": "newobj", "text": "t b f", "patching_rect": [ 320.0, 170.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "bang", "float" ] } },
			{ "box": { "id": "obj-16", "maxclass": "message", "text": "set loop_length $1", "patching_rect": [ 320.0, 210.0, 112.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-17", "maxclass": "message", "text": "set loop 1", "patching_rect": [ 440.0, 210.0, 66.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-18", "maxclass": "newobj", "text": "sel 1 0", "patching_rect": [ 520.0, 130.0, 50.0, 22.0 ], "numinlets": 3, "numoutlets": 3, "outlettype": [ "bang", "bang", "" ] } },
			{ "box": { "id": "obj-19", "maxclass": "message", "text": "call start_playing", "patching_rect": [ 520.0, 170.0, 105.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-20", "maxclass": "message", "text": "call stop_playing", "patching_rect": [ 585.0, 210.0, 103.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-21", "maxclass": "message", "text": "/awh/pong 2", "patching_rect": [ 660.0, 130.0, 80.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-22", "maxclass": "newobj", "text": "loadbang", "patching_rect": [ 740.0, 50.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "bang" ] } },
			{ "box": { "id": "obj-23", "maxclass": "newobj", "text": "live.path live_set", "patching_rect": [ 740.0, 85.0, 105.0, 22.0 ], "numinlets": 1, "numoutlets": 3, "outlettype": [ "", "", "" ] } },
			{ "box": { "id": "obj-24", "maxclass": "newobj", "text": "live.object", "patching_rect": [ 520.0, 250.0, 75.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-25", "maxclass": "button", "patching_rect": [ 860.0, 85.0, 20.0, 20.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-26", "maxclass": "comment", "text": "MANUAL RE-INIT — click after any reload/paste (loadbang won't refire; live.path silently breaks otherwise, same lesson as AWH Ducker.maxpat).", "patching_rect": [ 890.0, 88.0, 460.0, 20.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-27", "maxclass": "comment", "text": "FIRE: /awh/fire <trackIdx> <slotIdx> -> live_set tracks $1 clip_slots $2, call fire", "patching_rect": [ 1050.0, 105.0, 480.0, 18.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-28", "maxclass": "newobj", "text": "t l l", "patching_rect": [ 1050.0, 130.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-29", "maxclass": "newobj", "text": "unpack 0 0", "patching_rect": [ 1050.0, 170.0, 70.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "int", "int" ] } },
			{ "box": { "id": "obj-30", "maxclass": "newobj", "text": "expr (($i1 < 0) || ($i2 < 0)) ? 2 : 1", "patching_rect": [ 1050.0, 210.0, 230.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ] } },
			{ "box": { "id": "obj-31", "maxclass": "newobj", "text": "gate 2", "patching_rect": [ 1050.0, 250.0, 50.0, 22.0 ], "numinlets": 2, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-32", "maxclass": "newobj", "text": "t l l", "patching_rect": [ 1050.0, 290.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-33", "maxclass": "message", "text": "live_set tracks $1 clip_slots $2", "patching_rect": [ 1050.0, 330.0, 200.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-34", "maxclass": "newobj", "text": "live.path", "patching_rect": [ 1050.0, 370.0, 90.0, 22.0 ], "numinlets": 1, "numoutlets": 3, "outlettype": [ "", "", "" ] } },
			{ "box": { "id": "obj-35", "maxclass": "newobj", "text": "live.object", "patching_rect": [ 1050.0, 410.0, 75.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-36", "maxclass": "message", "text": "call fire", "patching_rect": [ 1270.0, 330.0, 75.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-37", "maxclass": "message", "text": "prepend /awh/status fire", "patching_rect": [ 1270.0, 370.0, 175.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-38", "maxclass": "message", "text": "prepend /awh/error bad-fire-index", "patching_rect": [ 1350.0, 170.0, 210.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-39", "maxclass": "comment", "text": "SCENE: /awh/scene <sceneIdx> -> live_set scenes $1, call fire", "patching_rect": [ 1050.0, 475.0, 480.0, 18.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-40", "maxclass": "newobj", "text": "t l l", "patching_rect": [ 1050.0, 500.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-41", "maxclass": "newobj", "text": "unpack 0", "patching_rect": [ 1050.0, 540.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "int" ] } },
			{ "box": { "id": "obj-42", "maxclass": "newobj", "text": "expr $i1 < 0 ? 2 : 1", "patching_rect": [ 1050.0, 580.0, 150.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "int" ] } },
			{ "box": { "id": "obj-43", "maxclass": "newobj", "text": "gate 2", "patching_rect": [ 1050.0, 620.0, 50.0, 22.0 ], "numinlets": 2, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-44", "maxclass": "newobj", "text": "t l l", "patching_rect": [ 1050.0, 660.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-45", "maxclass": "message", "text": "live_set scenes $1", "patching_rect": [ 1050.0, 700.0, 150.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-46", "maxclass": "newobj", "text": "live.path", "patching_rect": [ 1050.0, 740.0, 90.0, 22.0 ], "numinlets": 1, "numoutlets": 3, "outlettype": [ "", "", "" ] } },
			{ "box": { "id": "obj-47", "maxclass": "newobj", "text": "live.object", "patching_rect": [ 1050.0, 780.0, 75.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-48", "maxclass": "message", "text": "call fire", "patching_rect": [ 1270.0, 700.0, 75.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-49", "maxclass": "message", "text": "prepend /awh/status scene", "patching_rect": [ 1270.0, 740.0, 185.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-50", "maxclass": "message", "text": "prepend /awh/error bad-scene-index", "patching_rect": [ 1350.0, 540.0, 220.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-51", "maxclass": "comment", "text": "STOPCLIPS: /awh/stopclips <trackIdx> (-1=all) -> live_set[ tracks $1] call stop_all_clips", "patching_rect": [ 1050.0, 845.0, 480.0, 18.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-52", "maxclass": "newobj", "text": "t l l", "patching_rect": [ 1050.0, 870.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-53", "maxclass": "newobj", "text": "unpack 0", "patching_rect": [ 1050.0, 910.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "int" ] } },
			{ "box": { "id": "obj-54", "maxclass": "newobj", "text": "expr $i1 < -1 ? 2 : 1", "patching_rect": [ 1050.0, 950.0, 150.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "int" ] } },
			{ "box": { "id": "obj-55", "maxclass": "newobj", "text": "gate 2", "patching_rect": [ 1050.0, 990.0, 50.0, 22.0 ], "numinlets": 2, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-56", "maxclass": "newobj", "text": "t l l", "patching_rect": [ 1050.0, 1030.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-57", "maxclass": "newobj", "text": "unpack 0", "patching_rect": [ 1050.0, 1070.0, 60.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "int" ] } },
			{ "box": { "id": "obj-58", "maxclass": "newobj", "text": "sel -1", "patching_rect": [ 1050.0, 1110.0, 50.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "bang", "" ] } },
			{ "box": { "id": "obj-59", "maxclass": "message", "text": "live_set", "patching_rect": [ 1050.0, 1150.0, 70.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-60", "maxclass": "message", "text": "live_set tracks $1", "patching_rect": [ 1150.0, 1150.0, 150.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-61", "maxclass": "newobj", "text": "live.path", "patching_rect": [ 1050.0, 1190.0, 90.0, 22.0 ], "numinlets": 1, "numoutlets": 3, "outlettype": [ "", "", "" ] } },
			{ "box": { "id": "obj-62", "maxclass": "newobj", "text": "live.object", "patching_rect": [ 1050.0, 1230.0, 75.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-63", "maxclass": "message", "text": "call stop_all_clips", "patching_rect": [ 1300.0, 1070.0, 135.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-64", "maxclass": "message", "text": "prepend /awh/status stopclips", "patching_rect": [ 1300.0, 1110.0, 205.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-65", "maxclass": "message", "text": "prepend /awh/error bad-stopclips-index", "patching_rect": [ 1350.0, 910.0, 250.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-66", "maxclass": "comment", "text": "JUMP: /awh/jump <beats> -> live_set, set current_song_time $1", "patching_rect": [ 1050.0, 1275.0, 420.0, 18.0 ], "numinlets": 1, "numoutlets": 0 } },
			{ "box": { "id": "obj-67", "maxclass": "newobj", "text": "t l l", "patching_rect": [ 1050.0, 1300.0, 45.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
			{ "box": { "id": "obj-68", "maxclass": "message", "text": "live_set", "patching_rect": [ 1050.0, 1340.0, 70.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-69", "maxclass": "newobj", "text": "live.path", "patching_rect": [ 1050.0, 1380.0, 90.0, 22.0 ], "numinlets": 1, "numoutlets": 3, "outlettype": [ "", "", "" ] } },
			{ "box": { "id": "obj-70", "maxclass": "newobj", "text": "live.object", "patching_rect": [ 1050.0, 1420.0, 75.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-71", "maxclass": "message", "text": "set current_song_time $1", "patching_rect": [ 1270.0, 1340.0, 175.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } },
			{ "box": { "id": "obj-72", "maxclass": "message", "text": "prepend /awh/status jump", "patching_rect": [ 1270.0, 1380.0, 175.0, 22.0 ], "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ] } }
		],
		"lines": [
			{ "patchline": { "source": [ "obj-2", 0 ], "destination": [ "obj-3", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 0 ], "destination": [ "obj-5", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 1 ], "destination": [ "obj-6", 0 ] } },
			{ "patchline": { "source": [ "obj-6", 0 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 0 ], "destination": [ "obj-7", 0 ] } },
			{ "patchline": { "source": [ "obj-7", 0 ], "destination": [ "obj-8", 0 ] } },
			{ "patchline": { "source": [ "obj-8", 0 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 1 ], "destination": [ "obj-9", 0 ] } },
			{ "patchline": { "source": [ "obj-9", 0 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 2 ], "destination": [ "obj-13", 0 ] } },
			{ "patchline": { "source": [ "obj-13", 0 ], "destination": [ "obj-14", 0 ] } },
			{ "patchline": { "source": [ "obj-14", 0 ], "destination": [ "obj-24", 0 ] } },
			{ "patchline": { "source": [ "obj-13", 1 ], "destination": [ "obj-15", 0 ] } },
			{ "patchline": { "source": [ "obj-15", 1 ], "destination": [ "obj-16", 0 ] } },
			{ "patchline": { "source": [ "obj-16", 0 ], "destination": [ "obj-24", 0 ] } },
			{ "patchline": { "source": [ "obj-15", 0 ], "destination": [ "obj-17", 0 ] } },
			{ "patchline": { "source": [ "obj-17", 0 ], "destination": [ "obj-24", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 3 ], "destination": [ "obj-18", 0 ] } },
			{ "patchline": { "source": [ "obj-18", 0 ], "destination": [ "obj-19", 0 ] } },
			{ "patchline": { "source": [ "obj-18", 1 ], "destination": [ "obj-20", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 0 ], "destination": [ "obj-24", 0 ] } },
			{ "patchline": { "source": [ "obj-20", 0 ], "destination": [ "obj-24", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 4 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-21", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-22", 0 ], "destination": [ "obj-23", 0 ] } },
			{ "patchline": { "source": [ "obj-25", 0 ], "destination": [ "obj-23", 0 ] } },
			{ "patchline": { "source": [ "obj-23", 0 ], "destination": [ "obj-24", 1 ] } },
			{ "patchline": { "source": [ "obj-11", 0 ], "destination": [ "obj-12", 0 ] } },
			{ "patchline": { "source": [ "obj-11", 1 ], "destination": [ "obj-12", 1 ] } },
			{ "patchline": { "source": [ "obj-11", 0 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-11", 1 ], "destination": [ "obj-10", 1 ] } },
			{ "patchline": { "source": [ "obj-3", 5 ], "destination": [ "obj-28", 0 ] } },
			{ "patchline": { "source": [ "obj-28", 1 ], "destination": [ "obj-29", 0 ] } },
			{ "patchline": { "source": [ "obj-29", 1 ], "destination": [ "obj-30", 1 ] } },
			{ "patchline": { "source": [ "obj-29", 0 ], "destination": [ "obj-30", 0 ] } },
			{ "patchline": { "source": [ "obj-30", 0 ], "destination": [ "obj-31", 0 ] } },
			{ "patchline": { "source": [ "obj-28", 0 ], "destination": [ "obj-31", 1 ] } },
			{ "patchline": { "source": [ "obj-31", 0 ], "destination": [ "obj-32", 0 ] } },
			{ "patchline": { "source": [ "obj-31", 1 ], "destination": [ "obj-38", 0 ] } },
			{ "patchline": { "source": [ "obj-38", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-32", 1 ], "destination": [ "obj-33", 0 ] } },
			{ "patchline": { "source": [ "obj-33", 0 ], "destination": [ "obj-34", 0 ] } },
			{ "patchline": { "source": [ "obj-34", 0 ], "destination": [ "obj-35", 1 ] } },
			{ "patchline": { "source": [ "obj-32", 0 ], "destination": [ "obj-36", 0 ] } },
			{ "patchline": { "source": [ "obj-36", 0 ], "destination": [ "obj-35", 0 ] } },
			{ "patchline": { "source": [ "obj-32", 0 ], "destination": [ "obj-37", 0 ] } },
			{ "patchline": { "source": [ "obj-37", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 6 ], "destination": [ "obj-40", 0 ] } },
			{ "patchline": { "source": [ "obj-40", 1 ], "destination": [ "obj-41", 0 ] } },
			{ "patchline": { "source": [ "obj-41", 0 ], "destination": [ "obj-42", 0 ] } },
			{ "patchline": { "source": [ "obj-42", 0 ], "destination": [ "obj-43", 0 ] } },
			{ "patchline": { "source": [ "obj-40", 0 ], "destination": [ "obj-43", 1 ] } },
			{ "patchline": { "source": [ "obj-43", 0 ], "destination": [ "obj-44", 0 ] } },
			{ "patchline": { "source": [ "obj-43", 1 ], "destination": [ "obj-50", 0 ] } },
			{ "patchline": { "source": [ "obj-50", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-44", 1 ], "destination": [ "obj-45", 0 ] } },
			{ "patchline": { "source": [ "obj-45", 0 ], "destination": [ "obj-46", 0 ] } },
			{ "patchline": { "source": [ "obj-46", 0 ], "destination": [ "obj-47", 1 ] } },
			{ "patchline": { "source": [ "obj-44", 0 ], "destination": [ "obj-48", 0 ] } },
			{ "patchline": { "source": [ "obj-48", 0 ], "destination": [ "obj-47", 0 ] } },
			{ "patchline": { "source": [ "obj-44", 0 ], "destination": [ "obj-49", 0 ] } },
			{ "patchline": { "source": [ "obj-49", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 7 ], "destination": [ "obj-52", 0 ] } },
			{ "patchline": { "source": [ "obj-52", 1 ], "destination": [ "obj-53", 0 ] } },
			{ "patchline": { "source": [ "obj-53", 0 ], "destination": [ "obj-54", 0 ] } },
			{ "patchline": { "source": [ "obj-54", 0 ], "destination": [ "obj-55", 0 ] } },
			{ "patchline": { "source": [ "obj-52", 0 ], "destination": [ "obj-55", 1 ] } },
			{ "patchline": { "source": [ "obj-55", 0 ], "destination": [ "obj-56", 0 ] } },
			{ "patchline": { "source": [ "obj-55", 1 ], "destination": [ "obj-65", 0 ] } },
			{ "patchline": { "source": [ "obj-65", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-56", 1 ], "destination": [ "obj-57", 0 ] } },
			{ "patchline": { "source": [ "obj-57", 0 ], "destination": [ "obj-58", 0 ] } },
			{ "patchline": { "source": [ "obj-58", 0 ], "destination": [ "obj-59", 0 ] } },
			{ "patchline": { "source": [ "obj-58", 1 ], "destination": [ "obj-60", 0 ] } },
			{ "patchline": { "source": [ "obj-59", 0 ], "destination": [ "obj-61", 0 ] } },
			{ "patchline": { "source": [ "obj-60", 0 ], "destination": [ "obj-61", 0 ] } },
			{ "patchline": { "source": [ "obj-61", 0 ], "destination": [ "obj-62", 1 ] } },
			{ "patchline": { "source": [ "obj-56", 0 ], "destination": [ "obj-63", 0 ] } },
			{ "patchline": { "source": [ "obj-63", 0 ], "destination": [ "obj-62", 0 ] } },
			{ "patchline": { "source": [ "obj-56", 0 ], "destination": [ "obj-64", 0 ] } },
			{ "patchline": { "source": [ "obj-64", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 8 ], "destination": [ "obj-67", 0 ] } },
			{ "patchline": { "source": [ "obj-67", 1 ], "destination": [ "obj-68", 0 ] } },
			{ "patchline": { "source": [ "obj-68", 0 ], "destination": [ "obj-69", 0 ] } },
			{ "patchline": { "source": [ "obj-69", 0 ], "destination": [ "obj-70", 1 ] } },
			{ "patchline": { "source": [ "obj-67", 0 ], "destination": [ "obj-71", 0 ] } },
			{ "patchline": { "source": [ "obj-71", 0 ], "destination": [ "obj-70", 0 ] } },
			{ "patchline": { "source": [ "obj-67", 0 ], "destination": [ "obj-72", 0 ] } },
			{ "patchline": { "source": [ "obj-72", 0 ], "destination": [ "obj-4", 0 ] } }
		]
	}
}
