/**
 * `awh endless build`: validate an endless.yaml spec (every problem at
 * once, before any output, per docs/lessons-learned.md's "validate before
 * write, loud failures before partial output"), then emit the player:
 * index.html + player.js + the audio pools + endless-README.md. See
 * docs/design/endless-player.md for the format.
 */
import { existsSync } from "node:fs";
import { mkdir, readFile, copyFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseEndlessSpec, validateEndlessSpec, type EndlessSpec } from "@awh/core";
import { parseWavHeader, expectedLoopDurationSeconds } from "./wav.js";

const DURATION_TOLERANCE_MS = 25;
export const SINGLE_FILE_WARN_BYTES = 12 * 1024 * 1024;

/**
 * The player's static assets (player.js + the index.html template) live in
 * packages/cli/assets/endless/, a sibling of src/, so `tsc` never touches
 * or copies them (they're not TypeScript). Their path is resolved at
 * runtime relative to this compiled module's location (dist/endless/
 * build.js -> ../../assets/endless). `findLibraryRoot` and the `new
 * project` template copy in index.ts also resolve from where the code runs,
 * but they anchor to cwd; these assets ship with the package, so they
 * anchor to the package's install location.
 */
export function endlessAssetsDir(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, "..", "..", "assets", "endless");
}

function collectPoolFiles(spec: EndlessSpec): Set<string> {
  const files = new Set<string>();
  for (const section of spec.sections) {
    for (const pool of Object.values(section.pools)) {
      for (const file of pool) files.add(file);
    }
  }
  return files;
}

/**
 * Structural validation (parseEndlessSpec + validateEndlessSpec) plus the
 * file-level checks that need real files on disk: every pool file exists,
 * and every file's duration matches bars*4*60/bpm within +-25ms (pure RIFF
 * chunk math, see wav.ts). Returns every problem found, spec-dir-relative
 * paths kept alongside the parsed spec so callers can reuse both without
 * re-parsing.
 */
export async function checkEndlessSpecFile(
  specPath: string,
): Promise<{ spec: EndlessSpec; specDir: string; problems: string[] }> {
  const specDir = dirname(resolve(specPath));
  const yamlText = await readFile(specPath, "utf8");
  const spec = parseEndlessSpec(yamlText); // throws loudly on any structural/typo error
  const problems = validateEndlessSpec(spec);

  for (const section of spec.sections) {
    const expectedS = expectedLoopDurationSeconds(section.bars, spec.bpm);
    for (const [layerId, files] of Object.entries(section.pools)) {
      for (const file of files) {
        const abs = resolve(specDir, file);
        if (!existsSync(abs)) {
          problems.push(
            `section "${section.id}", layer "${layerId}": missing audio file "${file}" (resolved: ${abs})`,
          );
          continue;
        }
        let info;
        try {
          info = parseWavHeader(await readFile(abs));
        } catch (err) {
          problems.push(
            `section "${section.id}", layer "${layerId}", file "${file}": ${(err as Error).message}`,
          );
          continue;
        }
        const diffMs = Math.abs(info.durationSeconds - expectedS) * 1000;
        if (diffMs > DURATION_TOLERANCE_MS) {
          problems.push(
            `section "${section.id}", layer "${layerId}", file "${file}": duration ${info.durationSeconds.toFixed(3)}s ` +
              `does not match ${section.bars} bar(s) @ ${spec.bpm} BPM, sig 4/4 (expected ${expectedS.toFixed(3)}s ` +
              `+-${DURATION_TOLERANCE_MS}ms — off by ${diffMs.toFixed(1)}ms; loops must be bar-exact, see the README ` +
              `this build emits for baking reverb tails)`,
          );
        }
      }
    }
  }

  return { spec, specDir, problems };
}

function escapeForInlineScript(json: string): string {
  // A </script> substring inside embedded JSON would prematurely close the
  // tag under HTML parsing rules regardless of the tag's `type`, so escape it.
  return json.replace(/<\/script/gi, "<\\/script");
}

function readmeText(spec: EndlessSpec, singleFile: boolean, sizeBytes?: number): string {
  const lines: string[] = [
    `# ${spec.name} — endless player`,
    "",
    `Generated by \`awh endless build\` (docs/design/endless-player.md).`,
    "",
  ];
  if (singleFile) {
    lines.push(
      "One self-contained `index.html` — player.js and every audio pool file",
      "are inlined as `data:` URIs. Just open it directly (double-click, or",
      "`open index.html` / `xdg-open index.html`) — no server needed.",
      "",
    );
    if (sizeBytes !== undefined) {
      const mb = (sizeBytes / (1024 * 1024)).toFixed(1);
      lines.push(`File size: ${mb} MB.`);
      if (sizeBytes > SINGLE_FILE_WARN_BYTES) {
        lines.push(
          `**Over the 12 MB single-file guideline** — fine for a quick share, but`,
          `prefer the multi-file build (drop \`--single-file\`) for a real song's`,
          `full-length stems.`,
        );
      }
      lines.push("");
    }
  } else {
    lines.push(
      "This folder is a static site: `index.html` + `player.js` (ESM, zero",
      "deps) + the audio pools under `audio/`.",
      "",
      "## Listen",
      "",
      "Browsers block `fetch()` on `file://` pages, so serve this folder — don't",
      "just double-click `index.html`:",
      "",
      "```sh",
      "python3 -m http.server 8000",
      "```",
      "",
      "then open http://localhost:8000 in a browser and press Play.",
      "",
    );
  }
  lines.push(
    "## What you're hearing",
    "",
    `\`${spec.name}\` at ${spec.bpm} BPM, seed ${spec.seed === 0 ? "0 (fresh random performance each load)" : spec.seed}.`,
    `Sections: ${spec.sections.map((s) => `${s.id} (${s.bars} bars)`).join(", ")}.`,
    "",
    "The section picker, variant picker, and mute roller are pure, seeded",
    "functions of the spec (see `player.js`) — the live readout under Play",
    "always shows exactly what the grammar just decided. This is arrangement",
    "+ mix-fluctuation only: every sound is a pre-produced audio file the",
    "grammar arranges, never a note composed at playback.",
    "",
    "Loops must be bar-exact. If a source loop has a reverb/delay tail that",
    "would otherwise get cut at the loop boundary, render it with the tail",
    "OVERLAPPED back onto the start of the file (bounce bar-exact length,",
    "with the tail folded in) rather than trimmed off — `awh endless build`",
    "validates duration, not tail cleanliness, so a clipped tail will pass",
    "validation and still sound wrong.",
    "",
    `Regenerate any time: \`awh endless build <spec> -o <dir>${singleFile ? " --single-file" : ""}\`.`,
    "",
  );
  return lines.join("\n");
}

export interface BuildOptions {
  singleFile?: boolean;
}

export interface BuildResult {
  outDir: string;
  files: string[];
  singleFileBytes?: number;
}

/**
 * Validates everything (structural + every file's existence/duration),
 * throwing the full problem list if anything is wrong. Nothing is written
 * on failure. On success emits index.html (+ player.js + audio/ unless
 * --single-file, which inlines both) + endless-README.md into `outDir`.
 */
export async function buildEndlessPlayer(
  specPath: string,
  outDir: string,
  opts: BuildOptions = {},
): Promise<BuildResult> {
  const { spec, specDir, problems } = await checkEndlessSpecFile(specPath);
  if (problems.length > 0) {
    throw new Error(
      `endless build: ${problems.length} problem(s) found — fixed before writing anything:\n` +
        problems.map((p) => `  - ${p}`).join("\n"),
    );
  }

  const assets = endlessAssetsDir();
  const templateHtml = await readFile(join(assets, "index.html"), "utf8");
  const playerJs = await readFile(join(assets, "player.js"), "utf8");
  const poolFiles = [...collectPoolFiles(spec)].toSorted();

  await mkdir(outDir, { recursive: true });
  const written: string[] = [];

  if (opts.singleFile) {
    const specForEmbed: EndlessSpec = structuredClone(spec);
    for (const section of specForEmbed.sections) {
      for (const [layerId, files] of Object.entries(section.pools)) {
        section.pools[layerId] = await Promise.all(
          files.map(async (file) => {
            const data = await readFile(resolve(specDir, file));
            return `data:audio/wav;base64,${data.toString("base64")}`;
          }),
        );
      }
    }
    const html = templateHtml
      .replaceAll("__ENDLESS_TITLE__", spec.name)
      .replaceAll("__ENDLESS_SPEC_JSON__", escapeForInlineScript(JSON.stringify(specForEmbed)))
      .replaceAll(
        "<!--ENDLESS_PLAYER_SCRIPT_TAG-->",
        `<script type="module">\n${playerJs}\n</script>`,
      );
    const htmlPath = join(outDir, "index.html");
    await writeFile(htmlPath, html, "utf8");
    written.push(htmlPath);
    const sizeBytes = Buffer.byteLength(html, "utf8");
    await writeFile(join(outDir, "endless-README.md"), readmeText(spec, true, sizeBytes), "utf8");
    written.push(join(outDir, "endless-README.md"));
    return { outDir, files: written, singleFileBytes: sizeBytes };
  }

  const html = templateHtml
    .replaceAll("__ENDLESS_TITLE__", spec.name)
    .replaceAll("__ENDLESS_SPEC_JSON__", escapeForInlineScript(JSON.stringify(spec)))
    .replaceAll(
      "<!--ENDLESS_PLAYER_SCRIPT_TAG-->",
      `<script type="module" src="./player.js"></script>`,
    );
  await writeFile(join(outDir, "index.html"), html, "utf8");
  written.push(join(outDir, "index.html"));
  await writeFile(join(outDir, "player.js"), playerJs, "utf8");
  written.push(join(outDir, "player.js"));

  for (const file of poolFiles) {
    const from = resolve(specDir, file);
    const to = join(outDir, file);
    await mkdir(dirname(to), { recursive: true });
    await copyFile(from, to);
    written.push(to);
  }

  await writeFile(join(outDir, "endless-README.md"), readmeText(spec, false), "utf8");
  written.push(join(outDir, "endless-README.md"));

  return { outDir, files: written };
}
